import Head from 'next/head'
import Image from 'next/image'
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
import Box from '@mui/material/Box';
import Paper from '@mui/material/Paper';
import TextField from '@mui/material/TextField';
import styles from '../styles/Home.module.css'
import { SvgIcon, Icon, Typography, Input, Button } from '@mui/material';
import { textAlign } from '@mui/system';
import AppIcon from '../public/app.svg'
import { useEffect, useState } from 'react';

import { grey } from '@mui/material/colors';
import { Grid3x3 } from '@mui/icons-material';


// hier fehlt OG Bild
const CUSTO = "http://curious-stories.com/"
//hier wird Browser geprüft
const MEDIUM = "https://medium.com/@czmclaudiu/how-to-earn-200-per-day-in-passive-income-by-2022-6-ideas-618da6d31277"
const BI = "https://www.businessinsider.de/politik/welt/wer-mehr-als-373-grad-koerpertemperatur-hat-fliegt-raus-die-extremen-corona-regeln-chinas-bei-den-olympischen-spielen/"


export default function Home() {

  const [url, setUrl] = useState(BI);
  const [isValidUrl, setIsValidUrl] = useState(true)
  const [content, setContent] = useState("")

  const updateUrl = (value) => {
    if (validateUrl(value)){
      setUrl(value)
      setIsValidUrl(true)
    } else {
      setUrl("Please set valid URL") //delete later, only debug
      setIsValidUrl(false)
    }

  }

  const loadUrl = () => {
    fetch('./api/hello', {
      method: 'POST',
      body: JSON.stringify(url)
    })
      .then(e => e.json())
      .then(function(res){
        const ServerResponce = res.resp; 
        console.log(ServerResponce)
        //window.alert("loading 😀👉" + ServerResponce  + " 🚀")
        //setContent(ServerResponce);
      } )
  }

  function validateUrl(value) {
    return /^(?:(?:(?:https?|ftp):)?\/\/)(?:\S+(?::\S*)?@)?(?:(?!(?:10|127)(?:\.\d{1,3}){3})(?!(?:169\.254|192\.168)(?:\.\d{1,3}){2})(?!172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2})(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z\u00a1-\uffff0-9]-*)*[a-z\u00a1-\uffff0-9]+)(?:\.(?:[a-z\u00a1-\uffff0-9]-*)*[a-z\u00a1-\uffff0-9]+)*(?:\.(?:[a-z\u00a1-\uffff]{2,})))(?::\d{2,5})?(?:[/?#]\S*)?$/i.test(value);
  }

  const Feature = (content) => {
    return (                  
      <Paper style={{padding:'15px'}}>
      <img src="/placeholder.png" alt="me" width="64" height="64" />
    <Typography variant="h5">Right When You Need It</Typography>
    <Typography>See all of your appointments, work meetings and life events in one place so you know exactly where you need to be at any given time.</Typography>
    <Button>asd</Button></Paper>)
  } 

  return (
    <div className={styles.container}>
      <Head>
        <title>CreAItly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      </Head>

      <section className={styles.sectionBlue}>
        <main>
        
        <Container >
          <Grid container spacing={2} justifyContent="center" alignItems="center">
            <Grid item xs={6}>
                <img style={{height:'500px'}} src="/d_animated.svg"/>
            </Grid>

            <Grid item xs={6} textAlign={'center'}>
              <Grid
                container
                direction="column"
                justifyContent="center"
                alignItems="center"
                spacing={2}
              >
                <Grid item>
                  <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>Insert your Link here:</Typography>
                </Grid>
                <Grid item>
                  <Input defaultValue={url} onChange={(e)=> updateUrl(e.target.value)}/>
                </Grid>
                <Grid item>
                  <Button disabled={!isValidUrl} variant="contained"  onClick={loadUrl}>Load page</Button>
                </Grid>
                <Grid item>
                  <TextField
                    id="outlined-multiline-static"
                    label="Your content will be here someday 🤗"
                    multiline
                    rows={4}
                    value={content}
                  />
                </Grid>
                
              </Grid>
                
            </Grid>
            
          </Grid>

        </Container>
        </main>     
      </section>
      
      <section className={styles.section}>
        <Box style={{textAlign:'center'}}>
          <Typography variant="h5">In a Glance</Typography>
          <Typography variant="h3">What's Great About App Land?</Typography>
          <br></br>
          <br></br>
          <Container>
            <Grid container spacing={2}>
              <Grid item xs={4}>
                 
                  <Feature></Feature>
                 
              </Grid>

              <Grid item xs={4}>
                <Feature></Feature>
              </Grid>

              <Grid item xs={4}>                
                
              <Feature></Feature>
                 
                </Grid>

            </Grid>
          </Container>

        </Box>
      </section>
      
      <section className={styles.section}>
        
        <Container >
          <Grid container justifyContent="center" alignItems="center" spacing={2}>
            <Grid item xs={6}>
              <img style={{height:'500px'}} src="/d_feed.svg"/>
            </Grid>
            <Grid item xs={6}>
            <Grid
                container
                direction="column"
                justifyContent="center"
                alignItems=""
                spacing={2}
              >
                <Grid item><Typography variant="h3">Right When You Need It</Typography></Grid>
                <Grid item><Typography variant="h5">Right When You Need It</Typography></Grid>
                <Grid item><Typography>Right When You Need It</Typography></Grid>
                <Grid item><Button variant="contained">Learn More </Button></Grid>
              
              </Grid>
            </Grid>
          </Grid>
        </Container>
      </section>

      <section className={styles.section}>
        
        <Container >
          <Grid container justifyContent="center" alignItems="center" spacing={2}>

            <Grid item xs={6}>
            <Grid
                container
                direction="column"
                justifyContent="center"
                alignItems=""
                spacing={2}
              >
                <Grid item><Typography variant="h3">Right When You Need It</Typography></Grid>
                <Grid item><Typography variant="h5">Right When You Need It</Typography></Grid>
                <Grid item><Typography>Right When You Need It</Typography></Grid>
                <Grid item><Button variant="contained">Learn More </Button></Grid>
              
              </Grid>
            </Grid>

            <Grid item xs={6}>
              <img style={{height:'500px'}} src="/d_dashboard.svg"/>
            </Grid>

          </Grid>
        </Container>
      </section>

      <section className={styles.section} style={{backgroundColor:'#ECEEF1'}}>
        <Grid 
          container
          direction="column"
          justifyContent="center"
          alignItems="center"
          spacing={3}
         >
          <Grid item>
            <Grid container justifyContent="center" alignItems="center" spacing={1}>
              <Grid item xs={7}>
                <Typography variant="h5">“A very useful project management app. I use it every day.”</Typography>
                <Typography variant="h3">“A very useful project management app. I use it every day.”</Typography>
              </Grid>
              <Grid item xs={5}><img src={'/d_person-1.png'} ></img></Grid>
            </Grid>
          </Grid>

          <Grid item >
          <Grid container justifyContent="center" alignItems="center" spacing={6}>
              <Grid item xs={5}><img src={'/d_person-2.png'}></img></Grid>
              <Grid item xs={7}>
                <Typography variant="h5">“A very useful project management app. I use it every day.”</Typography>
                <Typography variant="h3">“A very useful project management app. I use it every day.”</Typography>
              </Grid>
            </Grid>
          </Grid>
        </Grid>
      </section>
      
      <section className={styles.section}>
      Blue Braker
      </section>

      <footer className={styles.footer}>
      Pre Footer
      </footer>

      <footer className={styles.footer}>
       footer
      </footer>
    </div>
  )
}
